
"""add is_admin to activation_codes

Revision ID: 8a3d6c1f2e4b
Revises: c19a8d87bc38
Create Date: 2026-06-27 10:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a3d6c1f2e4b"
down_revision: Union[str, None] = "c19a8d87bc38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activation_codes",
        sa.Column("is_admin", sa.Boolean(), nullable=False, server_default=sa.text("false"))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activation_codes", "is_admin")
    # ### end Alembic commands ###

