"""add creator_id to activation_codes

Revision ID: ca2ae254323e
Revises: 157c579d20eb
Create Date: 2026-06-26 11:03:21.657305

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ca2ae254323e"
down_revision: Union[str, None] = "157c579d20eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("activation_codes", sa.Column("creator_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "activation_codes", "users", ["creator_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "activation_codes", type_="foreignkey")
    op.drop_column("activation_codes", "creator_id")
    # ### end Alembic commands ###
