"""add template_runs table

Revision ID: d723673defcc
Revises: e1f2a3b4c5d6
Create Date: 2026-07-01 16:39:53.391774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd723673defcc'
down_revision: Union[str, None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('generated_prompt', sa.Text(), nullable=True),
    sa.Column('form_values_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_playbook_run_steps_run'), table_name='playbook_run_steps')
    op.drop_index(op.f('ix_playbook_runs_user_created'), table_name='playbook_runs')
    op.drop_index(op.f('ix_playbooks_creator_id'), table_name='playbooks')
    op.drop_index(op.f('ix_playbooks_status'), table_name='playbooks')
    op.drop_index(op.f('ix_playbooks_use_count_created_at'), table_name='playbooks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_playbooks_use_count_created_at'), 'playbooks', ['use_count', 'created_at'], unique=False)
    op.create_index(op.f('ix_playbooks_status'), 'playbooks', ['status'], unique=False)
    op.create_index(op.f('ix_playbooks_creator_id'), 'playbooks', ['creator_id'], unique=False)
    op.create_index(op.f('ix_playbook_runs_user_created'), 'playbook_runs', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_playbook_run_steps_run'), 'playbook_run_steps', ['run_id', 'step_order'], unique=False)
    op.drop_table('template_runs')
    # ### end Alembic commands ###
